// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwTApADUJ3cvqvlDHQfPqoaBPtftM9Uc',
    appId: '1:103516212841:web:1a7672c35749f4b80b5cf8',
    messagingSenderId: '103516212841',
    projectId: 'speech-therapy-58ce0',
    authDomain: 'speech-therapy-58ce0.firebaseapp.com',
    storageBucket: 'speech-therapy-58ce0.appspot.com',
    measurementId: 'G-XZ3HCT254M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuYQhHztaHRpoF2jEPfD3edIYWfLa-wo',
    appId: '1:103516212841:android:f0631e8cfc64f71b0b5cf8',
    messagingSenderId: '103516212841',
    projectId: 'speech-therapy-58ce0',
    storageBucket: 'speech-therapy-58ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqoXgZX4LCr7i99nQy0zDPbnDcTblXMo',
    appId: '1:103516212841:ios:a4e3c4adcb049e650b5cf8',
    messagingSenderId: '103516212841',
    projectId: 'speech-therapy-58ce0',
    storageBucket: 'speech-therapy-58ce0.appspot.com',
    iosClientId: '103516212841-jchp902p22sp17rs0rnpepthb2854p4m.apps.googleusercontent.com',
    iosBundleId: 'com.speechtherapy.speechtherapy',
  );
}
